res/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
path('',views.index,name='res.index'),
path('li/',views.client,name='res.testimonial'),
path('about/',views.about,name='res.about'),
path('booking/',views.booking,name='res.booking'),
path('menu/',views.menu,name='res.menu'),
path('service/',views.service,name='res.service'),
path('team/',views.team,name='res.team'),
path('contact/',views.contact,name='res.contact'),
path('profile/',views.profile,name='res.profile'),
path('ingredients/<int:fid>',views.ingredients,name='res.ingredients'),
path('create/',views.PCV.as_view(), name='res.reservation'),
path('complete/',views.complete,name='res.complete'),


]

restaurant/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from restaurant import settings

urlpatterns = [
    path('', include ('res.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
     

res/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class CategoryMenu(models.Model):
    name = models.CharField( max_length=255, unique=True)
    featured = models.BooleanField(default=False)
    order = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True ,null=False)
    updated_at = models.DateTimeField(auto_now=True, null=False)


    def __str__(self):
        return self.name

class Clients(models.Model):
   name = models.CharField(max_length=100)
   profession = models.CharField(max_length=100)
   image = models.ImageField(upload_to='static/img' , null=True , blank=True )
   created_at = models.DateTimeField(auto_now_add=True , null=True)
   updated_at = models.DateTimeField(auto_now=True, null=True)
   say = models.TextField()    
   
   

   def __str__(self):
        return self.name

class Foods(models.Model):
    name = models.CharField(max_length=255, unique=True)
    featured = models.BooleanField(default=False)
    description = models.TextField()
    image = models.ImageField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    price = models.FloatField()
    ingredient = models.TextField(null=True)
    categorymenu = models.ForeignKey(CategoryMenu,on_delete=models.CASCADE)

    def __str__(self):
        return self.name



class Reser(models.Model):
 user = models.ForeignKey(User, on_delete=models.CASCADE)
 name = models.CharField(max_length=100,null=True)
 email = models.EmailField(null=True)
 created_at = models.DateTimeField(auto_now_add=True , null=True)
 updated_at = models.DateTimeField(auto_now=True, null=True)
 datetime = models.CharField(max_length=100 ,null=True)
 number = models.IntegerField(null=True)
 s_r = models.TextField(null=True)


 def __str__(self):
        return self.name

    
    

   
   

res/forms.py
from django import forms
from . import models
from django.core.exceptions import ValidationError
import re


class CreateReser(forms.ModelForm):
    class Meta:
        model= models.Reser
        fields=['name' , 'email' , 'datetime' , 'number' , 's_r' ]
        
    
class Client(forms.ModelForm):
    class Meta:
        model= models.Clients
        fields='__all__'    

        
    def clean_name(self):
         name = self.cleaned_data.get('name')
         
         if len(name) < 3 or len(name) >10  or not re.match("^[a-zA-Z\ء-ي)]+$", name):  # تحقق من أن الاسم يحتوي على حرفين على الأقل
            raise forms.ValidationError("الاسم يجب أن يحتوي على 3 احرف على الأقل")
         return name
        
    def clean_say(self):
         say = self.cleaned_data.get('say')
         if len(say) < 15 or len(say) > 100 or not re.match("^[a-zA-Z\ء-ي)]+$",say):  
            raise forms.ValidationError("التعليق يجب أن يحتوي على 30 حرف على الأقل")
         return say
    
    def clean_profession(self):
        profession = self.cleaned_data.get('profession')
         
        if len(profession) < 3  or  len(profession) >10 or not re.match("^[a-zA-Z\ء-ي)]+$", profession):# تحقق من أن الاسم يحتوي على حرفين على الأقل
            raise forms.ValidationError("المهنة يجب أن تحتوي على 3 احرف على الأقل")
        return profession
    


    
    
                    
   
        

res/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Foods,CategoryMenu,Clients,Reser,User
from django.views.generic import ListView,CreateView
from . import forms
from . import models
from django.urls import reverse_lazy,reverse
from django.http import HttpResponse
from django.views.generic.edit import ModelFormMixin
from .forms import Client , CreateReser 
from accounts.forms import UserRegister
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import time

def index(request):
    foods = Foods.objects.filter(featured=True)
    return render(request, 'index.html',
                  {
                      'foods' : foods
                  }
                  
                  
                  )



def ingredients(request,fid):
    
    food=Foods.objects.get(pk=fid)
    
    return render(request, 'food_details.html',{
      'food':food,
    })
                  

def profile(request):

    p = request.user
   
   

    return render(request, 'profile.html',{
        'p':p,
        

    })


def about(request):

    return render(request, 'about.html')

def booking(request):

    tes =Reser.objects.filter(user_id=request.user.id)

    return render(request, 'booking.html',{
                  
                  'tes':tes
    }
                  )

def contact(request):

    return render(request, 'contact.html')

def menu(request):
    
   sand= Foods.objects.filter(categorymenu=1)
   drn= Foods.objects.filter(categorymenu=2)
   mel= Foods.objects.filter(categorymenu=3)
   return render(request, 'menu.html',{
       
    'sand': sand,
    'drn':drn,
    'mel':mel,
   

   })

def food_cards(request):
    
 foods = Foods.objects.select_related('categorymenu').all()

 return render(request, 'food_cards.html',{
       
     'foods':foods       


   })
     
    
def team(request):

    return render(request, 'team.html')

def complete(request):

    return render(request, 'complete.html')


def service(request):

    return render(request, 'service.html')

class PCV(LoginRequiredMixin, CreateView):
      model = models.Reser
      form_class = forms.CreateReser
      template_name= 'reservation.html'
      success_url = reverse_lazy('res.index')
      
      def form_valid(self, form):                                    #يطلع الحجز الخاص بالمستخدم
        form.instance.user = self.request.user
        return super().form_valid(form) 
      
       


    
    
def client(request):
    c = Clients.objects.all()
   
    form = Client()

    if request.method == 'POST':
        form = Client(request.POST)
        if form.is_valid():
            form.save()
            return redirect('res.testimonial')  # يمكنك تغيير 'success' إلى اسم الصفحة التي ترغب في توجيه المستخدم إليها بعد إضافة العميل
    

    return render(request, 'testimonial.html', {
        
        'form': form,
        'c':c
        })

      
      
      
     

     
        
    
      
      
        

      
      
 
 

res/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    
    <meta charset="utf-8" />
    <title>Restoran - Bootstrap Restaurant Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="keywords" />
    <meta content="" name="description" />

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon" />

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&family=Pacifico&display=swap"
      rel="stylesheet"
    />

    <!-- Icon Font Stylesheet -->
    
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet" />
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet" />
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />
    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <!-- Template Stylesheet -->
    <style>
      .card-img-top {
        height: 200px; /* ارتفاع الصورة */
        width: 100%; /* عرض الصورة */
        object-fit: cover; /* تغيير حجم الصورة دون تشويهها */
      }
    </style> 
  </head>

  <body>
  {% include 'parts/header.html' %}

  {% block content %}

  {% endblock %}

  {% include 'parts/footer.html' %}
<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"
><i class="bi bi-arrow-up"></i
></a>
</div>

<!-- JavaScript Libraries -->

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/wow/wow.min.js' %}"></script>
<script src="{% static 'lib/easing/easing.min.js' %}"></script>
<script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
<script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
<script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

<!-- Template Javascript -->

<script src="{% static 'js/main.js' %}"></script>

  </body>

</html>

res/templates/booking.html
{% extends 'base.html' %}

{% load static %}

{% block content %}


 Books

{% for tes in tes %}
<ul>  
  <p> 
Name: {{ tes.name }}</p> 
<p>
Email: {{ tes.email }}</p>
<p>
People Number: {{ tes.number }}</p>
<p>
Date: {{ tes.datetime }}</p>
<p>
add: {{ tes.s_r }}</p>
  
</ul>

____________________________________________

{% endfor %}


{% endblock %}

res/templates/complete.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<form method="post">
  {% csrf_token %}
  
  <button type="submit" name="confirm" value="Yes">Confirm</button>
  <button type="submit" name="confirm" value="لا">Cancel</button>
</form>


{% endblock %}


 

res/templates/food_cards.html
    
      <div class="col-md-3">
        <div class="card">
          <img src="{{ food.image.url }}" class="card-img-top" alt="...">
          <div class="card-body">
            <h6 class="card-title">{{ food.name }}</h6>
            <a href="{% url 'res.ingredients' food.id  %}" class="btn btn-primary">Food Details</a>
          </div>
          <div class="card-footer">
            <strong class="fw-bold text-success">{{ food.price }} $</strong>
          </div>
        </div>
      </div>
    

res/templates/form.html
<ul class="list-group mb-1">
{% for error in form.non_field_errors %}
<li class="list-group-item list-group-item-danger" > {{error|escape}} </li>
{% endfor %}
{% for field in form %}
 {% for error in field.errors %} 
<li class="list-group-item list-group-item-danger" > {{error|escape}} </li>
 {% endfor %}
{% endfor %}
</ul>

{% for field in form %}
<div class="mb-3">
    <label class="form-lable"> {{field.label}} </label>
    {{field}}

</div>
{% endfor %}

res/templates/index.html
{% extends 'base.html' %}


{% load static %}


{% block content %}

    
<div class="container-xxl py-5 bg-dark hero-header mb-5">
  <div class="container my-5 py-5">
    <div class="row align-items-center g-5">
      <div class="col-lg-6 text-center text-lg-start">
        <h1 class="display-3 text-white animated slideInLeft">
          Enjoy Our<br />Delicious Meal
        </h1>
        <p class="text-white animated slideInLeft mb-4 pb-2">
          Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam
          et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna
          dolore erat amet
        </p>
        <a href="{% url 'res.reservation' %}" class="btn btn-primary py-sm-3 px-sm-5 me-3 animated slideInLeft"
          >Book A Table</a
        >
      </div>
      <div class="col-lg-6 text-center text-lg-end overflow-hidden">
        <img class="img-fluid" src="{% static 'img/hero.png' %}" alt="" />
      </div>
    </div>
  </div>
</div>
</div>

<div class="container my-5">
<section>
  
<div class="col-md-12 mb-5">
<p class="h1 text-center text-secondary">Feauter Meals</p>
</div>
  
<div class="row">
  {% for food in foods %}
    {% include 'food_cards.html' %}
    {% endfor %}
  </div>
</div>
</section>

  


      
  {% endblock %}

res/templates/menu.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
{%  include 'menu_menu.html' %}
  <!-- Menu End -->

  {% endblock %}

res/templates/menu_menu.html
<style>
  .square-container {
    position: relative;
    width: 100%;
    padding-top: 100%; /* نسبة 1:1 - يمكن تغيير هذه القيمة لتغيير النسبة */
    background-color: #f0f0f0; /* لون خلفية افتراضي */
  }

  .square-content {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
  }

  .square-content img {
    width: 100%;
    height: 100%;
    object-fit: cover; /* لتغطية المحتوى بالكامل */
  }

  .square-content h5 {
    font-size: 1.5em; /* حجم العنوان */
  }

  .square-content small {
    font-size: 1em; /* حجم النص */
  }
</style>

<!-- Menu Start -->

<div class="container-xxl py-5">
    <div class="container">
      <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
        <h5 class="section-title ff-secondary text-center text-primary fw-normal">Our Testy Food</h5>
        <h1 class="mb-5">Food Menu</h1>
      </div>
      <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.1s">
        <ul class="nav nav-pills d-inline-flex justify-content-center border-bottom mb-5">
          <li class="nav-item">
            <a
              class="d-flex align-items-center text-start mx-3 ms-0 pb-3 active"
              data-bs-toggle="pill"
              href="#tab-1"
            >
              <i class="fa fa-coffee fa-2x text-primary"></i>
              <div class="ps-3">
                <small class="text-body">Our</small>
                <h6 class="mt-n1 mb-0">Drinks</h6>
              </div>
            </a>
          </li>
          <li class="nav-item">
            <a
              class="d-flex align-items-center text-start mx-3 pb-3"
              data-bs-toggle="pill"
              href="#tab-2"
            >
              <i class="fa fa-hamburger fa-2x text-primary"></i>
              <div class="ps-3">
                <small class="text-body">Our</small>
                <h6 class="mt-n1 mb-0">Sandwish</h6>
               </div>
            </a>
          </li>
          <li class="nav-item">
            <a
              class="d-flex align-items-center text-start mx-3 me-0 pb-3"
              data-bs-toggle="pill"
              href="#tab-3"
            >
              <i class="fa fa-utensils fa-2x text-primary"></i>
              <div class="ps-3">
                <small class="text-body">Our</small>
                <h6 class="mt-n1 mb-0">Meals</h6>
              </div>
            </a>
          </li>
        </ul>
        <div class="tab-content">
          <div id="tab-1" class="tab-pane fade show p-0 active">
            <div class="row g-4">
              {% for drn in drn %}
              <div class="col-lg-6">
                <div class="d-flex align-items-center">
                  <img
                    class="flex-shrink-0 img-fluid rounded"
                    src="{{drn.image.url}}"
                    alt=""
                    style="width: 80px"
                  />
                  <div class="w-100 d-flex flex-column text-start ps-4">
                    <h5 class="d-flex justify-content-between border-bottom pb-2">
                      <span>{{drn.name}}</span>
                      <span class="text-primary">{{drn.name}}</span>
                    </h5>
                    <small class="fst-italic"
                      >{{drn.description}}</small
                    >
                  </div>
                </div>
              </div>
            {% endfor %}
            </div>
          </div>
          <div id="tab-2" class="tab-pane fade show p-0">
            <div class="row g-4">
              {% for sand in sand %}
              <div class="col-lg-6">
                <div class="d-flex align-items-center">
                  <img
                    class="flex-shrink-0 img-fluid rounded"
                    src="{{sand.image.url}}"
                    alt=""
                    style="width: 80px"
                  />
                  <div class="w-100 d-flex flex-column text-start ps-4">
                    <h5 class="d-flex justify-content-between border-bottom pb-2">
                      <span>{{sand.name}}</span>
                      <span class="text-primary">{{sand.price}} $ </span>
                    </h5>
                    <small class="fst-italic"
                      >{{sand.description}}</small
                    >
                  </div>
                </div>
              </div>
             {% endfor %}
            </div>
          </div>
          <div id="tab-3" class="tab-pane fade show p-0">
            <div class="row g-4">
              {% for mel in mel %}
              <div class="col-lg-6">
                <div class="d-flex align-items-center">
                  <img
                    class="flex-shrink-0 img-fluid rounded"
                    src="{{mel.image.url}}"
                    alt=""
                    style="width: 80px"
                  />
                  <div class="w-100 d-flex flex-column text-start ps-4">
                    <h5 class="d-flex justify-content-between border-bottom pb-2">
                      <span>{{mel.name}}</span>
                      <span class="text-primary">{{mel.name}}</span>
                    </h5>
                    <small class="fst-italic"
                      >{{mel.description}}</small
                    >
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Menu End -->

  

res/templates/profile.html
{% extends 'base.html' %}

{% load static %}

{% block content %}


 <h1>Profile</h1>


<ul>  
  <p> 
First Name: {{ p.first_name }}</p>
<p>
Last Name:  {{ p.last_name }}   
</p>   
<p>
Username:  {{ p.username }}   
</p>
<p>
Email: {{ p.email }}</p>
  
</ul>

____________________________________________




{% endblock %}

res/templates/reservation.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<script src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>

<div class="container-xxl py-5 px-0 wow fadeInUp" data-wow-delay="0.1s">
    <div class="row g-0">
      <div class="col-md-6">
        <div class="video">
          <video width="100%" height="575" controls>
            <source src="{% static 'img/sss.mp4' %}" type="video/mp4">
            Your browser does not support the video tag.
        </video>
          </div>
      </div>
      <div class="col-md-6 bg-dark d-flex align-items-center">
        <div class="p-5 wow fadeInUp" data-wow-delay="0.2s">
          <h1 style="margin-top: -30px;" class="section-title ff-secondary text-primary fw-normal text-center">Laffah Garden</h1>
          <h3 class="text-white mb-4 text-center">Book A Table Online</h3>
          <form method="POST"  onsubmit="return confirm('Are you sure you want to submit the form? \n' + (parseInt(document.getElementById('id_number').value) <= 5 ? 'This will cost $3.' : 'This will cost $5.'));">
            {% csrf_token %}
            <ul class="list-group mb-1">
              {% for error in form.non_field_errors %}
              <li class="list-group-item list-group-item-danger" > {{error|escape}} </li>
              {% endfor %}
              {% for field in form %}
               {% for error in field.errors %} 
              <li class="list-group-item list-group-item-danger" > {{error|escape}} </li>
               {% endfor %}
              {% endfor %}
              </ul>
            <div class="row g-3">
              <div class="col-md-6">
                <div class="form-floating">
                  <input type="text" class="form-control" id="id_name" name="name" placeholder="Your Name" />
                  <label for="name">Your Name</label>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-floating">
                  <input
                    type="email"
                    class="form-control"
                    id="id_email"
                    name="email"
                    placeholder="Your Email"
                  />
                  <label for="email">Your Email</label>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-floating date" id="date3" data-target-input="nearest">
                    <input type="text" name="datetime" class="form-control datetimepicker-input" id="datetime" placeholder="Date & Time" data-target="#date3" data-toggle="datetimepicker" />
                    <label for="datetime">Date & Time</label>
                </div>
            </div>

              
              
              <div class="col-md-6">
                <div class="form-floating">
                  <input type="text" class="form-control" id="id_number" name="number" placeholder=">Number of People" />
                  <label for="number">Number of People</label>
                </div>
              </div>
              <div class="col-12">
                <div class="form-floating">
                  <textarea
                    class="form-control"
                    placeholder="Special Request"
                    id="id_s_r"
                    name="s_r"
                    style="height: 100px"
                  ></textarea>
                  <label for="s_r">Special Request</label>
                </div>
              </div>
              <div class="col-12">
                <button class="btn btn-primary w-100 py-3" type="submit">Book Now</button>

              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <div
    class="modal fade"
    id="videoModal"
    tabindex="-1"
    aria-labelledby="exampleModalLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog">
      <div class="modal-content rounded-0">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Youtube Video</h5>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>
        </div>
        <div class="modal-body">
          <!-- 16:9 aspect ratio -->
          <div class="ratio ratio-16x9">
            <iframe
              class="embed-responsive-item"
              src=""
              id="video"
              allowfullscreen
              allowscriptaccess="always"
              allow="autoplay"
            ></iframe>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Reservation end -->

  {% endblock %}

res/templates/service.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<!-- Service Start -->
<div class="container-xxl py-5">
    <div class="container">
      <div class="row g-4">
        <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
          <div class="service-item rounded pt-3">
            <div class="p-4">
              <i class="fa fa-3x fa-user-tie text-primary mb-4"></i>
              <h5>Master Chefs</h5>
              <p>Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam</p>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.3s">
          <div class="service-item rounded pt-3">
            <div class="p-4">
              <i class="fa fa-3x fa-utensils text-primary mb-4"></i>
              <h5>Quality Food</h5>
              <p>Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam</p>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.5s">
          <div class="service-item rounded pt-3">
            <div class="p-4">
              <i class="fa fa-3x fa-cart-plus text-primary mb-4"></i>
              <h5>Online Order</h5>
              <p>Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam</p>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.7s">
          <div class="service-item rounded pt-3">
            <div class="p-4">
              <i class="fa fa-3x fa-headset text-primary mb-4"></i>
              <h5>24/7 Service</h5>
              <p>Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Service End -->
  {% endblock %}

res/templates/signup.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h2>Sign Up</h2>
    <form action="/login" method="POST">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" id="username" name="username"><br><br>
      <label for="password">Password:</label>
      <input type="password" id="password" name="password"><br><br>
      <label for="password">Confirm Password:</label>
      <input type="password" id="confirmpassword" name="confirmpassword"><br><br>
      <input type="submit" value="Submit">
    </form>
  </div>

  <h2>Do you have account?</h2>
  <h2> <a href="{% url 'res.login' %}">Login</a> </h2>

  {% endblock %}